### ISSUE TITLE
Remove package namespace and rename to `sphinx-hep-pdgref`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/sphinxcontrib-hep-pdgref#30]
In https://github.com/ComPWA/sphinxcontrib-hep-pdgref/pull/29, it seems that the `sphinxcontrib.hep` namespace is causing problems. Generally, Python namespace packages are to be avoided, to it would be better to rename the package to `sphinx-hep-pdgref`.

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/sphinxcontrib-hep-pdgref/pull/32
- [x] Create a PyPI release for `sphinxcontrib-hep-pdgref` with a deprecation warning and a release note that links to `sphinx-hep-pdgref`
- [ ] https://github.com/ComPWA/sphinxcontrib-hep-pdgref/pull/31
- [x] Rename repository to [`sphinx-hep-pdgref`](https://github.com/ComPWA/sphinx-hep-pdgref)
- [x] Create a new PyPI release for [`sphinx-hep-pdgref`](https://pypi.org/project/sphinx-hep-pdgref)
```
